remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme 
title: jorg-j Page
raw: https://raw.githubusercontent.com/jorg-j/jorg-j.github.io/master/
show_downloads: true

sidebar:
  - index